/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class reptor_tbftc_ctroxy_CTroxy */

#ifndef _Included_reptor_tbftc_ctroxy_CTroxy
#define _Included_reptor_tbftc_ctroxy_CTroxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     reptor_tbftc_ctroxy_CTroxy
 * Method:    initialize
 * Signature: (BIIIZIIZ[B[B)J
 */
JNIEXPORT jlong JNICALL Java_reptor_tbftc_ctroxy_CTroxy_initialize
  (JNIEnv *, jobject, jbyte, jint, jint, jint, jboolean, jint, jint, jboolean, jbyteArray, jbyteArray);

/*
 * Class:     reptor_tbftc_ctroxy_CTroxy
 * Method:    resetHandshakeNative
 * Signature: (JSZLreptor/tbft/TroxyHandshakeResults;)V
 */
JNIEXPORT void JNICALL Java_reptor_tbftc_ctroxy_CTroxy_resetHandshakeNative
  (JNIEnv *, jobject, jlong, jshort, jboolean, jobject);

/*
 * Class:     reptor_tbftc_ctroxy_CTroxy
 * Method:    acceptNative
 * Signature: (JSLreptor/tbft/TroxyHandshakeResults;)V
 */
JNIEXPORT void JNICALL Java_reptor_tbftc_ctroxy_CTroxy_acceptNative
  (JNIEnv *, jobject, jlong, jshort, jobject);

/*
 * Class:     reptor_tbftc_ctroxy_CTroxy
 * Method:    processHandshakeInboundDataNative
 * Signature: (JSLjava/nio/ByteBuffer;IILreptor/tbft/TroxyHandshakeResults;)I
 */
JNIEXPORT jint JNICALL Java_reptor_tbftc_ctroxy_CTroxy_processHandshakeInboundDataNative
  (JNIEnv *, jobject, jlong, jshort, jobject, jint, jint, jobject);

/*
 * Class:     reptor_tbftc_ctroxy_CTroxy
 * Method:    retrieveHandshakeOutboundData
 * Signature: (JSLjava/nio/ByteBuffer;IILreptor/tbft/TroxyHandshakeResults;)I
 */
JNIEXPORT jint JNICALL Java_reptor_tbftc_ctroxy_CTroxy_retrieveHandshakeOutboundData
  (JNIEnv *, jobject, jlong, jshort, jobject, jint, jint, jobject);

/*
 * Class:     reptor_tbftc_ctroxy_CTroxy
 * Method:    saveStateNative
 * Signature: (JSLreptor/tbft/TroxyClientResults;)V
 */
JNIEXPORT void JNICALL Java_reptor_tbftc_ctroxy_CTroxy_saveStateNative
  (JNIEnv *, jobject, jlong, jshort, jobject);

/*
 * Class:     reptor_tbftc_ctroxy_CTroxy
 * Method:    openNative
 * Signature: (JSLreptor/tbft/TroxyClientResults;)V
 */
JNIEXPORT void JNICALL Java_reptor_tbftc_ctroxy_CTroxy_openNative
  (JNIEnv *, jobject, jlong, jshort, jobject);

/*
 * Class:     reptor_tbftc_ctroxy_CTroxy
 * Method:    initClientNative
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_reptor_tbftc_ctroxy_CTroxy_initClientNative
  (JNIEnv *, jobject, jlong, jshort);

/*
 * Class:     reptor_tbftc_ctroxy_CTroxy
 * Method:    processClientInboundDataNative
 * Signature: (JSLjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;IILreptor/tbft/TroxyClientResults;)I
 */
JNIEXPORT jint JNICALL Java_reptor_tbftc_ctroxy_CTroxy_processClientInboundDataNative
  (JNIEnv *, jobject, jlong, jshort, jobject, jint, jint, jobject, jint, jint, jobject);

/*
 * Class:     reptor_tbftc_ctroxy_CTroxy
 * Method:    retrieveClientOutboundDataNative
 * Signature: (JSLjava/nio/ByteBuffer;IILreptor/tbft/TroxyClientResults;)I
 */
JNIEXPORT jint JNICALL Java_reptor_tbftc_ctroxy_CTroxy_retrieveClientOutboundDataNative
  (JNIEnv *, jobject, jlong, jshort, jobject, jint, jint, jobject);

/*
 * Class:     reptor_tbftc_ctroxy_CTroxy
 * Method:    handleForwardedRequestNative
 * Signature: (JS[BIILjava/nio/ByteBuffer;IILreptor/tbft/TroxyClientResults;)I
 */
JNIEXPORT jint JNICALL Java_reptor_tbftc_ctroxy_CTroxy_handleForwardedRequestNative
  (JNIEnv *, jobject, jlong, jshort, jbyteArray, jint, jint, jobject, jint, jint, jobject);

/*
 * Class:     reptor_tbftc_ctroxy_CTroxy
 * Method:    handleRequestExecutedNative
 * Signature: (JSJLjava/nio/ByteBuffer;IIZLjava/nio/ByteBuffer;IILreptor/tbft/TroxyClientResults;)I
 */
JNIEXPORT jint JNICALL Java_reptor_tbftc_ctroxy_CTroxy_handleRequestExecutedNative
  (JNIEnv *, jobject, jlong, jshort, jlong, jobject, jint, jint, jboolean, jobject, jint, jint, jobject);

/*
 * Class:     reptor_tbftc_ctroxy_CTroxy
 * Method:    handleReplyNative
 * Signature: (JS[BIILreptor/tbft/TroxyClientResults;II)I
 */
JNIEXPORT jint JNICALL Java_reptor_tbftc_ctroxy_CTroxy_handleReplyNative
  (JNIEnv *, jobject, jlong, jshort, jbyteArray, jint, jint, jobject, jint, jint);

/*
 * Class:     reptor_tbftc_ctroxy_CTroxy
 * Method:    handleRepliesNative
 * Signature: (JSLjava/nio/ByteBuffer;IILreptor/tbft/TroxyClientResults;)V
 */
JNIEXPORT void JNICALL Java_reptor_tbftc_ctroxy_CTroxy_handleRepliesNative
  (JNIEnv *, jobject, jlong, jshort, jobject, jint, jint, jobject);

/*
 * Class:     reptor_tbftc_ctroxy_CTroxy
 * Method:    verifyProposalNative
 * Signature: (JI[BII)V
 */
JNIEXPORT void JNICALL Java_reptor_tbftc_ctroxy_CTroxy_verifyProposalNative
  (JNIEnv *, jobject, jlong, jint, jbyteArray, jint, jint);

/*
 * Class:     reptor_tbftc_ctroxy_CTroxy
 * Method:    verifyProposalsNative
 * Signature: (JI[B)V
 */
JNIEXPORT void JNICALL Java_reptor_tbftc_ctroxy_CTroxy_verifyProposalsNative
  (JNIEnv *, jobject, jlong, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
